name: CI/CD Pipeline - Visa Application

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/visa-application:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/visa-application:latest

      # Deploy on EC2 using SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Pull latest Docker image
            docker pull ${{ secrets.DOCKER_USERNAME }}/visa-application:latest

            # Stop and remove old container (if exists)
            docker stop visa-app || true
            docker rm visa-app || true

            # Run new container with environment variables from GitHub Secrets
            docker run -d -p 5001:5000 \
              -e MONGO_USER=${{ secrets.MONGO_USER }} \
              -e MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
              -e MONGO_HOST=${{ secrets.MONGO_HOST }} \
              -e MONGO_DB=${{ secrets.MONGO_DB }} \
              -e MONGO_COLLECTION=${{ secrets.MONGO_COLLECTION }} \
              --name visa-app ${{ secrets.DOCKER_USERNAME }}/visa-application:latest
